### ISSUE TITLE
sem_lock not implemented on android?

### ISSUE THREAD

**Issue by sohamghoshkaamwork** [wcchoi/swell.sh#1]
Trying to run this on lineageOS 16, using termux on a rooted phone. Keep running into the error after the python server starts up. (Probably at receiving the first request if I observed correctly.)

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/home/swell.sh/venv/lib/python3.8/lib-dynload/_multiprocessing.cpython-38.so)

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "app.py", line 471, in <module>
    executor = concurrent.futures.ProcessPoolExecutor()
  File "/data/data/com.termux/files/usr/lib/python3.8/concurrent/futures/process.py", line 555, in __init__
    self._call_queue = _SafeQueue(
  File "/data/data/com.termux/files/usr/lib/python3.8/concurrent/futures/process.py", line 165, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 67, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/synchronize.py", line 30, in <module>
    raise ImportError("This platform lacks a functioning sem_open" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
```

**Comment by wcchoi** [comment]
This is the limitation of Termux Python that it does not support multiprocessing

You can try to change this line from `app.py`:
https://github.com/wcchoi/swell.sh/blob/7435646486d5a93c35fa9319ce518d77453402fb/app.py#L471

To 
```
 executor = concurrent.futures.ThreadPoolExecutor() 

```

and see if it works

**Comment by sohamghoshkaamwork** [comment]
Thanks you @wcchoi 
That worked perfectly.
